{{- if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  source:
    path: giropops-senhas/helm
    repoURL: https://github.com/rafael-debug/descomplicando-gitops-no-kubernetes-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

{{- end }}